# The Neural network

In [4]:
import numpy as np
import tensorflow as tf

## Loading the data

In [5]:
npz = np.load('Screentime_train.npz')
train_inputs = npz['inputs'].astype(np.float32)
train_outputs = npz['targets'].astype(np.int64)

npz = np.load('Screentime_validation.npz')
validation_inputs = npz['inputs'].astype(np.float32)
validation_outputs = npz['targets'].astype(np.int64)

npz = np.load('Screentime_test.npz')
test_inputs = npz['inputs'].astype(np.float32)
test_outputs = npz['targets'].astype(np.int64)


In [6]:
train_inputs 

array([[ 1.9479529 , -0.44122273, -0.2530796 , ...,  1.040833  ,
         0.00714044, -0.02371331],
       [-0.5133594 , -0.7010028 , -0.6489009 , ...,  1.040833  ,
        -0.70690334, -0.6759458 ],
       [ 1.9479529 , -1.2657421 , -1.2817264 , ..., -0.96076894,
        -1.4209471 , -1.0672853 ],
       ...,
       [ 1.9479529 ,  1.252995  ,  1.1335168 , ..., -0.96076894,
         1.435228  ,  1.6720911 ],
       [-0.5133594 ,  1.3828851 ,  1.1041967 , ..., -0.96076894,
         1.435228  ,  1.9003725 ],
       [-0.5133594 ,  1.7951448 ,  1.4792496 , ..., -0.96076894,
         1.435228  ,  1.1176935 ]], dtype=float32)

In [10]:
validation_inputs

array([[-0.5133594 , -1.1414994 , -1.2096478 , -1.2509782 , -1.062108  ,
        -1.123166  , -0.96076894, -1.4209471 , -1.3607899 ],
       [ 1.9479529 , -0.50334406, -0.03073549,  0.01183222, -0.19178748,
         0.37629274,  1.040833  ,  0.00714044, -0.1541598 ],
       [-0.5133594 , -0.4638123 ,  0.19038692,  0.3089641 , -0.21053766,
         1.5425384 , -0.96076894,  0.00714044, -0.1541598 ],
       [-0.5133594 , -1.0567886 , -1.3562484 , -1.5109687 , -1.2246095 ,
         0.95941556, -0.96076894, -1.4209471 , -1.3281783 ],
       [-0.5133594 ,  1.597486  ,  1.5281165 ,  1.2003597 ,  1.0566615 ,
        -0.3734366 ,  1.040833  ,  1.435228  ,  1.6394795 ],
       [ 1.9479529 ,  0.3042331 ,  0.8781876 ,  0.7175204 ,  0.5722821 ,
        -0.70664966,  1.040833  ,  0.7211842 ,  0.23717968],
       [-0.5133594 ,  0.3098805 ,  0.87696594,  0.82894486,  0.8191593 ,
         0.95941556, -0.96076894,  0.7211842 ,  0.6285192 ],
       [-0.5133594 ,  0.6091923 ,  0.36386418,  0.6432375 ,  0

In [11]:
test_inputs

array([[-0.5133594 , -0.5485232 , -0.7283095 , -0.50814855, -0.56991595,
        -0.5400431 ,  1.040833  , -0.70690334, -0.90422714],
       [ 1.9479529 ,  1.5805439 ,  1.7125888 ,  1.534633  ,  1.5176033 ,
         1.0427188 , -0.96076894,  1.435228  ,  1.0524703 ],
       [-0.5133594 ,  0.6374293 ,  0.806109  ,  0.79180336,  0.6972832 ,
         1.7091448 , -0.96076894,  0.7211842 ,  0.5632959 ],
       [-0.5133594 , -0.78006625, -0.6330192 , -0.73099744, -0.8011681 ,
        -0.5400431 , -0.96076894, -0.70690334, -1.0672853 ],
       [-0.5133594 ,  0.6148397 ,  1.0125713 ,  0.9775108 ,  0.40821806,
        -0.70664966, -0.96076894,  0.7211842 ,  0.7589657 ],
       [-0.5133594 , -0.3847488 , -0.24697122,  0.19753964, -0.22303776,
        -1.4563789 , -0.96076894,  0.00714044, -0.4150528 ],
       [ 1.9479529 ,  0.3945914 ,  1.0651032 ,  0.6432375 ,  0.19571608,
        -0.5400431 ,  1.040833  ,  0.7211842 ,  0.6285192 ],
       [-0.5133594 , -1.107615  , -1.2072045 , -1.3995442 , -1

In [29]:
test_outputs

array([150, 510, 420, 120, 456, 240, 432, 114, 378, 372, 264, 102, 144,
        84, 312, 600, 240, 432,  96, 216, 162, 438,  78, 204, 366, 306,
       264,  96, 504, 288, 342, 300, 576, 144, 114, 396, 186,  96, 564,
       180, 366, 300, 126,  78, 426, 150, 588, 450, 168,  96, 372, 132,
       432, 462, 102, 150, 102,  72, 474, 366, 132, 102, 360, 222, 432,
       192, 126, 264, 204, 186], dtype=int64)

## Model:
Outline, Optimisers, loss, early stopping and training

In [ ]:

input_size = 9
output_size = 1
hidden_layer = 110

model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer, activation='relu', input_shape=(input_size,)),
    tf.keras.layers.Dense(hidden_layer, activation='relu'),
    tf.keras.layers.Dense(hidden_layer, activation='relu'),
    tf.keras.layers.Dense(hidden_layer, activation='relu'),
    tf.keras.layers.Dense(output_size)  # No activation for regression
])

# Compile the model with a suitable loss function and optimizer for regression
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

# Hyperparameters
batch_size = 64  # Smaller batch size for better generalization
epochs = 50  # Fewer epochs since we use early stopping

# Callbacks: EarlyStopping + Learning Rate Reduction
early_stopping = tf.keras.callbacks.EarlyStopping(
    patience=3,  # Wait for 3 epochs without improvement
    restore_best_weights=True  # Restore the best weights after stopping
)

reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',  # Monitor validation loss for adjustments
    factor=0.5,  # Reduce LR by half if no improvement
    patience=2,  # Wait 2 epochs before reducing LR
    min_lr=1e-6  # Minimum learning rate
)

# Compile model with optimized optimizer and loss
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),  # Tuned optimizer
    loss='mse',  # Suitable for regression
    metrics=['accuracy']  # Mean Absolute Error as additional metric
)

# Train the model
history = model.fit(
    train_inputs, train_outputs,
    batch_size=batch_size,
    epochs=epochs,
    validation_data=(validation_inputs, validation_outputs),
      # Add ReduceLROnPlateau
    verbose=0
)

In [59]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Initialize lists to store predictions and actual outputs
predictions = []
actual_outputs = []

# Iterate through the test inputs and collect predictions
for i in range(len(test_inputs)):
    # Reshape each test input to match the model's expected input shape (1, 9)
    input_data = np.array([test_inputs[i]])  # Shape: (1, 9)
    
    # Predict screen time for the input
    predicted_output = model.predict(input_data)[0][0]  # Extract scalar value

    # Store predicted and actual output for evaluation
    predictions.append(predicted_output)
    actual_outputs.append(test_outputs[i])

# Convert predictions and actuals to numpy arrays
predictions = np.array(predictions)
actual_outputs = np.array(actual_outputs)

# Calculate MAE and MSE
mae = mean_absolute_error(actual_outputs, predictions)
mse = mean_squared_error(actual_outputs, predictions)

# print(f"Mean Absolute Error (MAE): {mae}")
# print(f"Mean Squared Error (MSE): {mse}")
print(f"Average Accuracy is: {100-mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━

In [61]:
from sklearn.metrics import r2_score

r2 = r2_score(actual_outputs, predictions)
print(f"R² Score: {r2}")

R² Score: 0.9977557063102722


In [62]:
rmse = np.sqrt(mse)
print(f"RMSE: {rmse}")

RMSE: 7.152931448265133
